### ISSUE TITLE
 Running the checkpoint for 'mimic_cxr' results in error

### ISSUE THREAD

**Issue by Ammexm** [zhjohnchan/R2Gen#3]
When running the checkpoint, an error occurs. Why is it that running the checkpoint for 'iu_xray' works fine, but running the checkpoint for 'mimic_cxr' results in the following error?

RuntimeError: Error(s) in loading state_dict for R2GenModel:
	size mismatch for encoder_decoder.model.tgt_embed.0.lut.weight: copying a param with shape torch.Size([4336, 512]) from checkpoint, the shape in current model is torch.Size([3595, 512]).
	size mismatch for encoder_decoder.logit.weight: copying a param with shape torch.Size([4336, 512]) from checkpoint, the shape in current model is torch.Size([3595, 512]).
	size mismatch for encoder_decoder.logit.bias: copying a param with shape torch.Size([4336]) from checkpoint, the shape in current model is torch.Size([3595]).

**Comment by 1benv** [comment]
I have the same problem,how do you slove it?  I delete these layers,but the result is bad.

**Comment by Ammexm** [comment]
> I have the same problem,how do you slove it? I delete these layers,but the result is bad.

because the annotation of mimic is not match

**Comment by 1benv** [comment]
Do you use the R2Gen MIMIC or&nbsp;physionet MIMIC？ I can't acquire the R2Gen MIMIC,so I filter the annotation to use physionet MIMMIC.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhjohnchan/R2Gen"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月15日(星期三) 上午10:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhjohnchan/R2Gen]  Running the checkpoint for 'mimic_cxr' results in error (Issue #3)





  
I have the same problem,how do you slove it? I delete these layers,but the result is bad.
  
because the annotation of mimic is not match

**Comment by 1benv** [comment]
I can not understand why it is not match the annotation,how do you solve the problem?

**Comment by wizardlancet** [comment]
Same, "size mismatch for encoder_decoder.model.tgt_embed.0.lut.weight: copying a param with shape torch.Size([4336, 512]) from checkpoint, the shape in current model is torch.Size([327, 512])." Do you solve the problem? thanks
